slc:
  image: tuyakhov/loopback
  volumes:
    - .:/code
  working_dir: /code
  entrypoint: slc
  command: --help
nodemon:
  image: tuyakhov/loopback
  volumes:
    - .:/code
  working_dir: /code
  entrypoint: nodemon
  command: -L .
  environment:
    - PORT=3000
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017
  ports:
    - "3000:3000"
  links:
    - mongodb:mongodb
arc:
  image: tuyakhov/loopback
  volumes:
    - .:/code
  working_dir: /code
  entrypoint: slc
  command: arc
  environment:
    - PORT=51459
  ports:
    - "51459:51459"
npm:
  image: tuyakhov/loopback
  volumes:
   - .:/code
  working_dir: /code
  entrypoint: npm
  command: install
mocha:
  image: tuyakhov/loopback
  volumes:
   - .:/code
  working_dir: /code
  entrypoint: mocha
  command: ./tests --recursive
  environment:
    NODE_ENV: test
mongodb:
  image: mongo
  restart: unless-stopped
  ports:
    - "27017:27017"