slc:
  image: tuyakhov/loopback
  volumes:
   - .:/code
  entrypoint: slc
  command: run
  ports:
    - "3000:3000"
arc:
  image: tuyakhov/loopback
  volumes:
   - .:/code
  entrypoint: slc
  command: arc
  ports:
    - "51459:51459"
npm:
  image: tuyakhov/loopback
  volumes:
   - .:/code
  working_dir: /code
  entrypoint: npm
  command: install